# Material You Desktop Palette
WALLPAPER="/home/Krish/.wallpaper/Nezuko Kamado.png"
PRIMARY="#e183c2"
ON_PRIMARY="#121214"
PRIMARY_CONTAINER="#401b34"
SECONDARY="#d8a5ca"
BACKGROUND="#130f12"
SURFACE="#1f181d"
SURFACE_VARIANT="#2c2028"
SURFACE_SELECTED="#401b34"
ON_SURFACE="#FFFFFF"
ON_SURFACE_VARIANT="#A5A5AA"
OUTLINE="#412f3b"
OUTLINE_SUBTLE="#25252a"
ERROR="#FF6B6B"
GNOME_ACCENT="pink"
