# Material You Hyprland Borders
$primary = rgb(e183c2)
$secondary = rgb(d8a5ca)
$surface = rgb(1f181d)
$outline = rgb(412f3b)
$active_border = rgb(e183c2) rgb(d8a5ca) 45deg
$inactive_border = rgba(412f3baa)
