# Material You Kitty Theme
foreground #FFFFFF
background #130f12
selection_foreground #130f12
selection_background #e183c2
cursor #e183c2
active_border_color #e183c2
inactive_border_color #412f3b
color4 #e183c2
color12 #e183c2
