# Material You Hyprland & Hyprlock Colors
$primary = rgb(f2e2b0)
$secondary = rgb(dbada3)
$surface = rgb(1f1e18)
$surface_variant = rgb(2c2920)
$background = rgb(13120f)
$outline = rgb(413c2f)
$active_border = rgb(f2e2b0) rgb(dbada3) 45deg
$inactive_border = rgba(413c2faa)
