[Theme]
Current=hyprland-sddm
CursorTheme=Bibata-Modern-Ice
CursorSize=24

[General]
InputMethod=qtvirtualkeyboard
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/hyprland-sddm/components/,QT_IM_MODULE=qtvirtualkeyboard,XCURSOR_THEME=Bibata-Modern-Ice,XCURSOR_SIZE=24
